version: '3.8'

services:
  crypto:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 31415:31415
    environment:
      - SERVER_PORT=31415
    command: ./mvnw spring-boot:run